const users = [
    {
        username: 'thinh',
        password: 'thinh24',
        name: 'Vương Thịnh',
        date: '24/03/1999',
        gender: 'Male',
        address: 'Thái Bình',
        email: 'thinh234@gmail.com',
        position: 'HRNhanvien',
        wage: 3000,
        department: 'Bu1',
    },
    {
        username: 'minh',
        password: 'minh21',
        name: 'Phạm Minh',
        date: '21/03/1999',
        gender: 'Male',
        address: 'Thái Bình',
        email: 'minh234@gmail.com',
        position: 'HRKho',
        wage: 2000,
        department: 'Bu2',
    },
    {
        username: 'long',
        password: 'long22',
        name: 'Văn Long',
        date: '22/03/1999',
        gender: 'Male',
        address: 'Thái Bình',
        email: 'long234@gmail.com',
        position: 'HRKho',
        wage: 4000,
        department: 'Bu3',
    },
    {
        username: 'truong',
        password: 'truong20',
        name: 'Xuân Trường',
        date: '20/03/1999',
        gender: 'Male',
        address: 'Thái Bình',
        email: 'truong234@gmail.com',
        position: 'HRNhanvien',
        wage: 5000,
        department: 'Bu4',
    },
];